@startuml
title Database
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "investments" as investment {
  *id : integer
  name : text
  value: double
  *category_id : integer <<FK>>
}

entity "categories" as category {
  *id : integer
  name : text
}

investment }|--|| category
@enduml
