@baseUrl  = http://localhost:3000
@createdInvestmentId = {{createInvestment.response.body.$.id}}

### Create a new Investment

# @name createInvestment
POST {{baseUrl}}/investments
Content-Type: application/json

{
  "name": "Tesouro IPCA 2029",
  "value": 100,
  "category_id": 3
}

### Read all Investments

GET {{baseUrl}}/investments

### Read a Investment

GET {{baseUrl}}/investments/{{createdInvestmentId}}

### Update a Investment

PUT {{baseUrl}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro IPCA 2029",
  "value": 200,
  "category_id": 3
}

### Delete a Investment

DELETE {{baseUrl}}/investments/{{createdInvestmentId}}
